# Configuration file for TravisCI

language: python
python: 3.7

env:
  global:
    # Sphinx HTML builddir
    - HTML_BUILDDIR=build/dirhtml
    # GSHHG and DCW version
    - GSHHG_VERSION=2.3.7
    - DCW_VERSION=1.1.4
    # set GMT_VERSION to fetch GMT archive tarball from the GMT repository.
    # Available values are:
    # - master: build the latest master branch
    # - 6.0: build the lastest 6.0 branch
    # - 6.0.0: build the 6.0.0 release
    - GMT_VERSION=6.0.0
    # URL of the current documentation
    - GMT_DOC_VERSION=6.0
    # GMT install location
    - GMT_INSTALL_PREFIX=${HOME}/GMT-${GMT_VERSION}
    # TeXLive install location
    - TEXLIVE_INSTALL_PREFIX=${HOME}/.TinyTeX
    # PATH
    - PATH=${GMT_INSTALL_PREFIX}/bin:${TEXLIVE_INSTALL_PREFIX}/bin/x86_64-linux:${PATH}

# Cache the installed GMT and TeXLive to save time
cache:
  pip: true
  directories:
    - ${TEXLIVE_INSTALL_PREFIX}
    - ${GMT_INSTALL_PREFIX}

# Only build pushes to select branches and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
  only:
    - master
    # Regex to build versioned branches, e.g. 5.4, 6.1
    - /^\d+\.\d+$/

# Install dependencies for building GMT
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - libcurl4-gnutls-dev
      - libnetcdf-dev
      - libgdal-dev
      - libfftw3-dev
      - libpcre3-dev
      - liblapack-dev
      - ghostscript
      - curl

install:
  # Install pngquant
  - sudo snap install core pngquant
  # Install Python dependencies
  - pip install -r requirements.txt
  # Install SourceCodePro fonts for PDF
  - curl -sSL https://raw.githubusercontent.com/seisman/install/master/install-SourceCodePro.sh | bash
  # Install tinytex (https://github.com/yihui/tinytex)
  - if [ ! -x "${TEXLIVE_INSTALL_PREFIX}/bin/x86_64-linux/tlmgr" ]; then
      wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh;
      tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth
          float wrapfig parskip capt-of needspace xcolor enumitem xindy fandol
          pdftexcmds;
    fi
  # Install GMT
  - if [ ! -x "${GMT_INSTALL_PREFIX}/bin/gmt" ]; then
      source ci/install-gmt.sh;
    fi
  - xelatex --version
  - gmt --version

script:
  # build html and PDF
  - make build
  # Optimize PNG files to reduce file sizes
  - bash ci/image_optimize.sh ${HTML_BUILDDIR}/_images/*.png

deploy:
  provider: script
  script: bash ci/deploy-gh-pages.sh
  skip_cleanup: true
  on:
    branch:
      - master
      # Regex to deploy on versioned branches, e.g. 5.4, 6.1
      - /^\d+\.\d+$/
