name: gmtdocs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.6.0
  - gawk
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - sphinx_rtd_theme
  - pip
  - pip:
    - sphinxcontrib.datatemplates
    - Pillow
