name: gmt-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.4.0
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - sphinx_rtd_theme
  - pip
  - pip:
    - sphinx-cjkspace
    - sphinxcontrib.datatemplates

