name: gmtdocs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.5.0
  - gawk
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-design=0.5.0
  - sphinx_rtd_theme<3
  - pip
  - pip:
    - sphinxcontrib.datatemplates
