name: Build documentation

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python packages
        run: pip install -r requirements.txt

      #- name: Install GMT dependencies
      #  run: |
      #    sudo apt-get install --no-install-recommends --no-install-suggests \
      #         cmake libcurl4-gnutls-dev libnetcdf-dev gdal-bin libgdal-dev \
      #         libfftw3-dev libpcre3-dev liblapack-dev libblas-dev libglib2.0-dev ghostscript

      - name: Install GMT dependencies
        run: |
          brew update
          brew install netcdf curl netcdf gdal fftw pcre2 ghostscript

      - name: Install TeXLive
        run: |
          wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh;
          tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth \
                        float wrapfig parskip capt-of needspace xcolor enumitem xindy fandol \
                        pdftexcmds upquote oberdiek caption

      - name: Build GMT
        run: |
          curl https://raw.githubusercontent.com/GenericMappingTools/gmt/master/ci/build-gmt.sh | bash
          # Add to PATH
          echo "${GMT_INSTALL_DIR}/bin" >> $GITHUB_PATH
        env:
          GMT_INSTALL_DIR: ${{ github.workspace }}/GMT
          GMT_GIT_REF: 6.1.1

      - name: Build documentaiton
        run: |
          make build
